databases:
  - name: Sample_DB
    databaseName: sample_db_o0at
    user: Sample_app
    region: singapore

services:
  - type: web
    name: Sample_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Sample_app
          property: connectionString
      - key: <%= ENV['SECRET_KEY_BASE'] %>
        sync: false
