databases:
  - name: dpg-ciajjr59aq007t99m1og-a
    databaseName: sample_db_b8qj
    user: sample_db_b8qj_user
    region: singapore

services:
  - type: web
    name: sample_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
